#!/usr/bin/env ansible-playbook

# This is example of per-host playbook.
# Create '<hostname>.yml' with host specific configuration.

- name: apply default role
  gather_facts: false
  connection: local
  hosts: localhost
  roles:

  - role: hostname
    vars:
      hostname: localhost

  - role: timezone
    vars:
      timezone: Europe/Warsaw

  - role: locale

  - role: unscd

  - role: system_groups

  - role: connman

  - role: resolve_dns_via_localhost

  - role: sshd
    vars:
      no_password_login: True

  - role: dnsmasq
    vars:
      upstream: connman

  - role: system_user
    vars:
      user: foo
      group: users
      additional_groups: audio,video

  - role: clean_tmp_dirs

  - role: disable_wireless_power_saving

  - role: dispatch-conf

  - role: user_configs
    vars:
      users:
      - root
      - foo
      deploy:
      - zsh
      - vim
      - tmux
      - colordiff
      - gnupg

  - role: pam_limits

  - role: in_home_tmpdir

  - role: default_umask_077

  - role: noclear_tty_on_boot

  - role: virtual_memory_tune

  - role: package.mask
