- assert:
    that:
    - user is defined

- include_role: 
  name: common_set_user_home_dir
  vars:
    user: '{{ user }}'

- name: set user's shell to /bin/zsh
  user:
    name: '{{ user }}'
    shell: /bin/zsh

- name: user's zshrc deployment
  copy:
    src: DOTzshrc
    dest: '{{ user_home_dir }}/.zshrc'
    owner: '{{ user }}'
    mode: 0600
