- assert:
    that:
    - user is defined

- name: query for home dir of user 
  getent:
    database: passwd
    key: '{{ user }}'

- name: set user_home_dir variable
  set_fact:
    user_home_dir: '{{ getent_passwd[user][4] }}'

- name: user's .tmux.conf deployment
  copy:
    src: DOTtmux.conf
    dest: '{{ user_home_dir }}/.tmux.conf'
    owner: '{{ user }}'
    mode: 0600
