- assert:
    that:
    - user is defined

- include_role:
    name: common_set_user_home_dir

- name: user's .tmux.conf deployment
  copy:
    src: DOTtmux.conf
    dest: '{{ user_home_dir }}/.tmux.conf'
    owner: '{{ user }}'
    mode: 0600
