- include_role:
    name: check_for_binary
  vars:
    binary: /usr/sbin/dnsmasq

- name: validate upstream variable
  assert:
    that:
    - upstream in ['connman', 'google', 'opendns', 'cloudflare']

- name: dnsmasq.conf
  notify: restart dnsmasq
  template:
    src: etc_dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
