# One can set git_name and git_email in playbook's vars or in inventory/group_vars/all/main.yml of conf-mgmt-private.

- name: .gitconfig deployment
  template:
    src: DOTgitconfig.j2
    dest: '{{ user_home_dir }}/.gitconfig'
    owner: '{{ user }}'
    group: '{{ user_group_id }}'
    mode: 0600
