- assert:
    that:
    - user is defined

- name: query for home dir of user
  getent:
    database: passwd
    key: '{{ user }}'

- name: set user_home_dir variable
  set_fact:
    user_home_dir: '{{ getent_passwd[user][4] }}'

- assert:
    that:
    - user_home_dir != ""

- debug:
    msg: 'user: {{ user }}'

- debug:
    msg: 'home dir: {{ user_home_dir }}'

- include_tasks: zsh.yml
  when: '"zsh" in deploy'

- include_tasks: tmux.yml
  when: '"tmux" in deploy'

- include_tasks: vim.yml
  when: '"vim" in deploy'
