- name: set user's shell to /bin/zsh
  user:
    name: '{{ user }}'
    shell: /bin/zsh

- name: .zshrc deployment
  copy:
    src: DOTzshrc
    dest: '{{ user_home_dir }}/.zshrc'
    owner: '{{ user }}'
    mode: 0600
