- name: ensure ~/.gnupg exist
  file:
    path: '{{ user_home_dir }}/.gnupg'
    state: directory
    mode: 0700
    owner: '{{ user }}'
    group: '{{ user_group_id }}'

- name: gpg.conf deployment
  copy:
    src: DOTgnupg_gpg.conf
    dest: '{{ user_home_dir }}/.gnupg/gpg.conf'
    owner: '{{ user }}'
    group: '{{ user_group_id }}'
    mode: 0600

- name: gpg-agent.conf deployment
  copy:
    src: DOTgnupg_gpg-agent.conf
    dest: '{{ user_home_dir }}/.gnupg/gpg-agent.conf'
    owner: '{{ user }}'
    group: '{{ user_group_id }}'
    mode: 0600
